theme = "base16_transparent"

[editor]
line-number = "relative"
bufferline = "always"
color-modes = true
auto-save = true

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

"A-left" = "unindent"
"A-down" = ['ensure_selections_forward', 'extend_to_line_bounds', 'extend_char_right', 'extend_char_left', 'delete_selection', 'add_newline_below', 'move_line_down', 'replace_with_yanked']
"A-up"= ['ensure_selections_forward', 'extend_to_line_bounds', 'extend_char_right', 'extend_char_left', 'delete_selection', 'move_line_up', 'add_newline_above', 'move_line_up', 'replace_with_yanked']
"A-right" = "indent"

"A-h" = "unindent"
"A-j" = ['ensure_selections_forward', 'extend_to_line_bounds', 'extend_char_right', 'extend_char_left', 'delete_selection', 'add_newline_below', 'move_line_down', 'replace_with_yanked']
"A-k"= ['ensure_selections_forward', 'extend_to_line_bounds', 'extend_char_right', 'extend_char_left', 'delete_selection', 'move_line_up', 'add_newline_above', 'move_line_up', 'replace_with_yanked']
"A-l" = "indent"

C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"

"C-left" = "select_prev_sibling"
"C-down" = "shrink_selection"
"C-up" = "expand_selection"
"C-right" = "select_next_sibling"

[keys.insert]
"C-s" = ":w"